services:
  practica1cs:
    image: mcr.microsoft.com/dotnet/aspnet:8.0 
    container_name: practica1cs_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: >
      bash -c "dotnet restore && dotnet build && dotnet run --urls=http://0.0.0.0:8000"
    restart: unless-stopped


