services:
  practica1cs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practica1cs_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

# Asegúrate de tener un Dockerfile en la raíz del proyecto para que funcione el build.

