name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Build and run tests with Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  build-image:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with Compose
        run: |
          docker compose build

      - name: Tag Docker image
        run: |
          # Reemplaza 'app' por el nombre del servicio en tu docker-compose.yml si es diferente
          docker tag $(docker compose images -q app) ghcr.io/${{ github.repository }}/app:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          # Reemplaza 'app' por el nombre del servicio en tu docker-compose.yml si es diferente
          docker push ghcr.io/${{ github.repository }}/app:latest
